inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - db/schema.rb
    - bin/spring
    - bin/rake
    - bin/rails
    - 'vendor/bundle/**/*'

Lint/AssignmentInCondition:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
