inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - db/schema.rb
    - 'db/migrate/**/*'
    - bin/spring
    - bin/rake
    - bin/rails
    - 'vendor/bundle/**/*'

Lint/AssignmentInCondition:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 6

